server:
  port: 8888

spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/MustafaSoyuer/Java13ConfigServer.git"
          default-label: "main"
          skip-ssl-validation: true
          username: "MustafaSoyuer"
          password: "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"
