server:
  port: 9094

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: UserProfile
      username: bilgeUser
      password: bilgeUser*

logging:
  level:
    org.springframework: info
    com.mustafa: info
#    root: trace
#  file:
#    name: user-service.log
#    max-size: 1MB

userservice:
  deger1: "1. Değer"
  deger2: "2. Değer"
  listem:
    bir: "bu ilk değer"
    iki: "bu ikinci"

ahmetamcanasilsin:
  iyiyim: "sen nasilsin"